# Generated by Django 5.0.1 on 2024-01-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
            ],
            options={"verbose_name": "Рубрика", "verbose_name_plural": "Рубрики",},
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(default=0, verbose_name="Лайки"),
                ),
                (
                    "shares",
                    models.PositiveIntegerField(default=0, verbose_name="Поделиться"),
                ),
            ],
            options={
                "verbose_name": "Метаданные",
                "verbose_name_plural": "Метаданные",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Фото",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Содержание")),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        choices=[(False, "Черновик"), (True, "Опубликовано")],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Интересные статьи",
                "verbose_name_plural": "Интересные статьи",
                "ordering": ["-time_create"],
            },
        ),
        migrations.CreateModel(
            name="TagPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(db_index=True, max_length=100, verbose_name="Тег"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
            ],
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги",},
        ),
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads_images", verbose_name="Изображение"
                    ),
                ),
            ],
        ),
    ]
