# Generated by Django 4.1.7 on 2024-03-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254)),
                ("body", models.TextField(verbose_name="Комментарий")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Статус")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                        verbose_name="Статья",
                    ),
                ),
            ],
            options={"ordering": ["created"],},
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created"], name="posts_comme_created_aa6d8f_idx"
            ),
        ),
    ]
